kind: pipeline
type: docker
name: Test

platform:
  os: linux
  arch: arm64

steps:

- name: Change permissions to user
  image: drone/git
  commands:
  - chown -R 1000:1000 .

- name: Test
  image: voidbuffer/devtools:latest
  commands:
  - make

