repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  # - id: check-shebang-scripts-are-executable
  - id: check-merge-conflict
  - id: fix-encoding-pragma

- repo: local
  hooks:
  - id: dos2unix
    name: dos2unix
    entry: bash scripts/dos2unix.sh
    args: [""]
    language: system
    pass_filenames: false
