.PHONY: clean All

All:
	@echo "----------Building project:[ HSM - Debug ]----------"
	@"$(MAKE)" -f  "HSM.mk"
clean:
	@echo "----------Cleaning project:[ HSM - Debug ]----------"
	@"$(MAKE)" -f  "HSM.mk" clean
